import { Brain, RefreshCcw } from 'lucide-react'

interface MLModelIndicatorProps {
  modelName: string
  accuracy?: string
  lastTrained?: string
  lastUpdated?: Date
  onRefresh?: () => void
  isRefreshing?: boolean
}

export function MLModelIndicator({ 
  modelName, 
  accuracy = '94.3',
  lastTrained = 'Oct 20, 2024',
  lastUpdated,
  onRefresh,
  isRefreshing = false
}: MLModelIndicatorProps) {
  return (
    <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-blue-600 dark:bg-blue-500 rounded-lg flex items-center justify-center">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <p className="font-semibold text-gray-900 dark:text-gray-100">
              {modelName}
            </p>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Accuracy: {accuracy}% | Last trained: {lastTrained}
            </p>
            {lastUpdated && (
              <p className="text-xs text-gray-500 dark:text-gray-500 mt-1">
                Updated: {lastUpdated.toLocaleTimeString()}
              </p>
            )}
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span className="text-xs text-green-600 dark:text-green-400 font-medium">
              Active
            </span>
          </div>
          {onRefresh && (
            <button
              onClick={onRefresh}
              disabled={isRefreshing}
              className="p-2 hover:bg-blue-100 dark:hover:bg-blue-800 rounded-lg transition-colors disabled:opacity-50"
              title="Refresh Predictions"
            >
              <RefreshCcw className={`w-4 h-4 text-blue-600 dark:text-blue-400 ${isRefreshing ? 'animate-spin' : ''}`} />
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

interface PredictionCardProps {
  title: string
  text: string
  confidence: number
  timestamp: Date
  priority?: 'high' | 'medium' | 'low'
}

export function PredictionCard({ title, text, confidence, timestamp, priority = 'medium' }: PredictionCardProps) {
  const priorityColors = {
    high: 'border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20',
    medium: 'border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/20',
    low: 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800'
  }

  return (
    <div className={`rounded-lg p-6 border ${priorityColors[priority]}`}>
      <div className="flex items-start justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
          {title}
        </h3>
        <div className="flex flex-col items-end gap-1">
          <span className="text-xs text-gray-500 dark:text-gray-400">
            Confidence
          </span>
          <div className="flex items-center gap-2">
            <div className="w-16 h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
              <div 
                className="h-full bg-green-500 transition-all duration-500"
                style={{ width: `${confidence}%` }}
              ></div>
            </div>
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              {confidence}%
            </span>
          </div>
        </div>
      </div>
      
      <div className="space-y-2">
        <p className="text-gray-700 dark:text-gray-300">
          {text}
        </p>
        
        <div className="flex items-center gap-4 text-xs text-gray-500 dark:text-gray-400">
          <span className="flex items-center gap-1">
            <Brain className="w-3 h-3" />
            Generated by AI
          </span>
          <span>
            {timestamp.toLocaleString()}
          </span>
        </div>
      </div>
    </div>
  )
}
